name: mishwar
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.6+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_swiper: ^1.1.6
  url_launcher: ^6.0.12
  flutter_phoenix: ^1.0.0
  sqflite: ^1.3.2+4
  http: ^0.13.3
  flutter_polyline_points: ^0.2.6
  shared_preferences: ^2.0.8
  toast: ^0.1.5
  flutter_google_places: ^0.3.0
  dotted_border: ^2.0.0+1
  image_picker: ^0.8.4+2
  flutter_share: ^1.0.5
  dio: ^4.0.0
  flutter_html: ^2.1.3
  path: ^1.8.0
  http_parser: ^4.0.0
  geocoding: ^2.0.1
  firebase_messaging: ^10.0.8
  firebase_core: ^1.7.0
  country_code_picker: ^2.0.2
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  font_awesome_flutter: ^9.1.0
  fcm_config: ^3.1.1
  geolocator: ^7.6.2
  google_maps_flutter: ^2.0.10
  map_launcher: ^2.1.1
  provider: ^6.0.1
  connectivity: ^3.0.6
  intl: ^0.17.0
  keyboard_dismisser: ^3.0.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.1.0
#  flutter_tap_payment: ^0.0.4
  rename: ^2.0.1
  # Show Message in Screens
  fluttertoast: ^8.1.1
  # Easy Loading
  flutter_easyloading: ^3.0.5
  # Snack Bar
  bot_toast: ^4.0.3
  # Payment
  flutter_tap_payment:
    path: ../flutter_tap_payment-0.0.4


  webview_flutter: ^2.0.4
  #  go_sell_sdk_flutter: ^2.1.8

  #  hyperpay: ^0.0.8-alpha
  #    git:
  #      url: https://github.com/nyartech/hyperpay.git
  #google_maps_place_picker: ^0.9.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  sizer: ^2.0.15
dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon_image.jpg"
  adaptive_icon_background: "#FFFFFFFF"


dev_dependencies:
  flutter_test:
    sdk: flutter
  dotted_line: ^3.0.1
  mobx_codegen: ^2.0.3









# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/slider/
    - images/icon/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: mishwarfont
      fonts:
        - asset: fonts/mishwarfont.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages